/*
 * Turns the Natural Earth world map into SVG paths keyed by country code.
 *
 * Run by hand when the map data changes: `node tools/buildWorldPaths.js`. The output is
 * committed, so the interface ships plain path strings — no TopoJSON to parse in the
 * browser and no geometry library in the bundle.
 *
 * Needs `npm install --no-save world-atlas topojson-client` first. Neither is a dependency
 * of Ackee, because neither is used at runtime.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'

// eslint-disable-next-line import-x/no-extraneous-dependencies -- installed on demand, see above
import { feature } from 'topojson-client'

const require = createRequire(import.meta.url)

// 110m is the coarsest of the three. On a card-sized map the finer ones add megabytes and
// no visible detail.
const source = JSON.parse(await readFile(require.resolve('world-atlas/countries-110m.json'), 'utf8'))
const countries = feature(source, source.objects.countries).features

const WIDTH = 1000
const HEIGHT = 500

// Equirectangular: longitude and latitude map straight onto x and y. Not a flattering
// projection, but it needs no library and the shapes stay recognisable.
// Rounded to whole units. At this size one unit is about a third of a degree, which is
// invisible on a card and roughly halves the size of the generated file.
const project = ([lon, lat]) => [Math.round(((lon + 180) / 360) * WIDTH), Math.round(((90 - lat) / 180) * HEIGHT)]

const ring = (points) => {
  const projected = []

  for (const point of points) {
    const [x, y] = project(point)
    const previous = projected.at(-1)

    // Rounding makes neighbouring points collapse onto each other. Keeping them would
    // only lengthen the path.
    if (previous != null && previous[0] === x && previous[1] === y) continue

    projected.push([x, y])
  }

  // Fewer than three distinct points is no longer a shape.
  if (projected.length < 3) return ''

  return `M${projected.map((point) => point.join(' ')).join('L')}Z`
}

const toPath = (geometry) => {
  if (geometry.type === 'Polygon') return geometry.coordinates.map((points) => ring(points)).join('')

  return geometry.coordinates.map((polygon) => polygon.map((points) => ring(points)).join('')).join('')
}

// Natural Earth names do not all match the ones Intl uses, so the exceptions are listed.
const ALIASES = {
  'United States of America': 'US',
  'Dem. Rep. Congo': 'CD',
  'Congo': 'CG',
  'Central African Rep.': 'CF',
  'Dominican Rep.': 'DO',
  'Eq. Guinea': 'GQ',
  'S. Sudan': 'SS',
  'Solomon Is.': 'SB',
  'Bosnia and Herz.': 'BA',
  'Czechia': 'CZ',
  'Côte d’Ivoire': 'CI',
  "Côte d'Ivoire": 'CI',
  'Falkland Is.': 'FK',
  'Fr. S. Antarctic Lands': 'TF',
  'N. Cyprus': 'CY',
  'Somaliland': 'SO',
  'W. Sahara': 'EH',
  'eSwatini': 'SZ',
  'Myanmar': 'MM',
  'Taiwan': 'TW',
  'Vietnam': 'VN',
  'Laos': 'LA',
  'North Korea': 'KP',
  'South Korea': 'KR',
  'Russia': 'RU',
  'Turkey': 'TR',
  'Iran': 'IR',
  'Syria': 'SY',
  'Venezuela': 'VE',
  'Bolivia': 'BO',
  'Tanzania': 'TZ',
  'Moldova': 'MD',
  'Macedonia': 'MK',
  'Kosovo': 'XK',
  'Palestine': 'PS',
  'Brunei': 'BN',
  'Trinidad and Tobago': 'TT',
}

const names = new Intl.DisplayNames(['en'], { type: 'region' })
const RETIRED = new Set(['AN', 'BU', 'CS', 'DD', 'FX', 'NT', 'QU', 'SU', 'TP', 'UK', 'YD', 'YU', 'ZR'])
const byName = new Map()

for (let first = 65; first <= 90; first++) {
  for (let second = 65; second <= 90; second++) {
    const code = String.fromCodePoint(first, second)

    if (RETIRED.has(code) === true) continue

    try {
      const name = names.of(code)

      if (name != null && name !== code) byName.set(name.toLowerCase(), code)
    } catch {
      // Not a region code.
    }
  }
}

const paths = {}
const missing = []

for (const country of countries) {
  const name = country.properties.name
  const code = ALIASES[name] ?? byName.get(String(name).toLowerCase())

  if (code == null) {
    missing.push(name)
    continue
  }

  paths[code] = toPath(country.geometry)
}

const body = Object.keys(paths)
  .toSorted()
  .map((code) => `  ${code}: '${paths[code]}',`)
  .join('\n')

await writeFile(
  'src/ui/scripts/constants/worldPaths.js',
  `// Generated by tools/buildWorldPaths.js from Natural Earth data via world-atlas.
// Do not edit by hand: run the script again instead.
//
// Equirectangular projection on a ${WIDTH}×${HEIGHT} viewBox, keyed by ISO 3166-1 alpha-2.
export const WIDTH = ${WIDTH}
export const HEIGHT = ${HEIGHT}

export default {
${body}
}
`,
)

console.log(`countries: ${Object.keys(paths).length}`)
if (missing.length > 0) console.log(`unmatched: ${missing.join(', ')}`)
